package com.logplatform.dto;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Response DTO for GET /logs/clusters/summary.
 *
 * Wraps every field of {@link LogClusterResult} and adds one extra field:
 * {@code aiSummary} — a plain-English explanation generated by the Groq LLM.
 *
 * Design choice — composition over inheritance:
 *   Rather than extending LogClusterResult, this class accepts a LogClusterResult
 *   in its constructor and delegates all getters to it.  This avoids tight coupling
 *   between the two DTOs and keeps Jackson serialisation straightforward (no need
 *   to worry about polymorphic type handling).
 */
public class LogClusterSummary {

    private final LogClusterResult cluster;

    /**
     * AI-generated plain-English explanation of the cluster.
     *
     * Set to "Summary unavailable" if the Groq API call failed (network error,
     * invalid key, rate limit, etc.) — the endpoint never crashes due to an
     * AI failure.
     */
    private final String aiSummary;

    public LogClusterSummary(LogClusterResult cluster, String aiSummary) {
        this.cluster   = cluster;
        this.aiSummary = aiSummary;
    }

    // -------------------------------------------------------------------------
    // Getters — Jackson serialises every public getter as a JSON field.
    // The field names intentionally mirror those of LogClusterResult so the
    // response shape is flat and easy to consume.
    // -------------------------------------------------------------------------

    /** @see LogClusterResult#getServiceName() */
    public String getServiceName() { return cluster.getServiceName(); }

    /** @see LogClusterResult#getLogLevel() */
    public String getLogLevel() { return cluster.getLogLevel(); }

    /** @see LogClusterResult#getTimeBucketStart() */
    public LocalDateTime getTimeBucketStart() { return cluster.getTimeBucketStart(); }

    /** @see LogClusterResult#getCount() */
    public int getCount() { return cluster.getCount(); }

    /** @see LogClusterResult#getSampleMessages() */
    public List<String> getSampleMessages() { return cluster.getSampleMessages(); }

    /**
     * The Groq-generated 1-2 sentence explanation of this cluster.
     * Focuses on likely cause and urgency.
     */
    public String getAiSummary() { return aiSummary; }
}
